name: ✨ Cypress Tests & Deploy Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 🧪 Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress with Mochawesome
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
        run: |
          npx cypress run \
            --reporter mochawesome \
            --reporter-options reportDir=mochawesome-report,overwrite=false,html=true,json=true

      - name: Upload mochawesome-report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: mochawesome-report

  deploy:
    name: 🚀 Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download mochawesome-report
        uses: actions/download-artifact@v3
        with:
          name: mochawesome-report
          path: ./mochawesome-report

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages

      - name: Copy report to repo root
        run: |
          rm -rf ./*
          cp -R mochawesome-report/* .

      - name: Commit & Push
        run: |
          git add .
          git commit -m "🔄 Atualiza relatório Mochawesome" || echo "No changes to commit"
          git push origin gh-pages --force

      - name: Return to main
        run: git checkout main
