name: ✨ Cypress Tests & Deploy Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 🧪 Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress with Mochawesome
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
        run: |
          npx cypress run \
            --reporter mochawesome \
            --reporter-options reportDir=mochawesome-report,overwrite=false,html=true,json=true

      - name: Upload mochawesome-report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report
          retention-days: 1

  deploy:
    name: 🚀 Deploy to GitHub Pages
    needs: test
    if: github.ref == 'refs/heads/main'  # Executa apenas no main
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mochawesome-report
          path: ./mochawesome-report

      - name: Setup Pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update report
        run: |
          rm -rf gh-pages/*
          cp -R mochawesome-report/* gh-pages/
        working-directory: .

      - name: Deploy to GitHub Pages
        working-directory: gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "🔄 Atualiza relatório Mochawesome - $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin gh-pages
